### ISSUE TITLE
Great project with incredible potential

### ISSUE THREAD

**Issue by RaulRG** [SteveSandersonMS/dotnet-wasi-sdk#18]
Hello Steve,
I just watched your video where you asked for some feedback. For me, this is one of the most interesting projects in the .NET space (and this says a lot about it). Using a very light runtime or krustlet with Kubernetes and wasm-based applications is like a dream come true!
I hope this project will go out of experimental status and grow to "official" one.

GREAT JOB!! You are indeed doing innovation in the .NET space

**Comment by jonathanperis** [comment]
This can open so many doors on the .NET ecossystem that it can't be ignored. Please Steve move foward with this and let's engage for this can be a part of .NET main stack

**Comment by SteveSandersonMS** [comment]
Thanks @RaulRG and @jonathanperis! I appreciate the feedback.

(Closing to tidy up the backlog, but feel free to comment further if anyone wishes)

**Comment by Biztactix-Ryan** [comment]
I think a lot of the talks have missed the massive potential for this, They've touched on some of the aspects... 

- Think of WASI Embedded in SQL Server... Instead of Stored Procedures, you can embed a webassembly module that runs the queries and returns it however you want.

- Think of WASI Embedded into RabbitMQ, Spin up an instance of the code per message, handle it and spin down

-Think of Embedding Code on Routers using WASI, to do deep packet inspection, or DNS Redirecting, Or Ad Filtering, Unlimited Potential

- Cloud would finally make sense, No more managing fleets of operating systems running your docker containers, But spinning up individual Wasi code for every web request at all edge locations around the world

- Think GUI Framework for True Native, Cross Platform Apps

It's what Java was supposed to be, you know with actual security, Write Once, Run Everywhere, Secure....
With Fast.ly and Cloudflare already integrating webassembly, And Shopify running the tests last year, showing, that you can run a new instance in less than 100 MicroSeconds - https://shopify.engineering/shopify-webassembly

I'm beyond excited... This is honestly the future of cloud... a truly transformative development, Unifies all the languages under a single architecture, to support all architectures.

**Comment by kopetan-ms** [comment]
> I think a lot of the talks have missed the massive potential for this, They've touched on some of the aspects...
> 
> * Think of WASI Embedded in SQL Server... Instead of Stored Procedures, you can embed a webassembly module that runs the queries and returns it however you want.
> * Think of WASI Embedded into RabbitMQ, Spin up an instance of the code per message, handle it and spin down
> * Think of Embedding Code on Routers using WASI, to do deep packet inspection, or DNS Redirecting, Or Ad Filtering, Unlimited Potential
> * Cloud would finally make sense, No more managing fleets of operating systems running your docker containers, But spinning up individual Wasi code for every web request at all edge locations around the world
> * Think GUI Framework for True Native, Cross Platform Apps
> 
> It's what Java was supposed to be, you know with actual security, Write Once, Run Everywhere, Secure.... With Fast.ly and Cloudflare already integrating webassembly, And Shopify running the tests last year, showing, that you can run a new instance in less than 100 MicroSeconds - https://shopify.engineering/shopify-webassembly
> 
> I'm beyond excited... This is honestly the future of cloud... a truly transformative development, Unifies all the languages under a single architecture, to support all architectures.

Completely agree!
